### ISSUE TITLE
How to align reads with different read groups in a single BWA MEM run?

### ISSUE THREAD

**Issue by serge2016** [lh3/bwa#149]
What `bwa mem` will do if I give it two files `sample1_PE_1.fastq.gz` and `sample1_PE_2.fastq.gz`, containing several read groups? How can I tell `bwa` to save original read groups and to process them separately?

According to http://chipster.csc.fi/manual/bwa-mem-with-index-building.html:
> It is possible to give the tool more than one FASTQ file/file pair. The tool will run the alignment for each file/file pair separately, and finally merge the resulting BAM files.
But I can't understand, how to save original read groups from those files!

Here this is also not shown:
https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/#step-2-bwa-alignment-bwa-0715-samtools-131

**Comment by mp15** [comment]
This is where you report bugs rather than ask for support, I would recommend bio-bwa-help@sourceforge.net for this kind of question. In any case if you have more than one read group you need to first separate them into separate (pairs of?) FASTQ files by read group. You can then run BWA separately for each read group (pair of?) FASTQs using the -R to set a different ID for each read group. You will then have one SAM/BAM for each read group with @RG tags indicating which read group  a read is from, you can thus concatenate or otherwise combine the resulting SAM/BAM files to make a single SAM/BAM for that sample.

**Comment by serge2016** [comment]
@mp15 thank you for the answer!
