### ISSUE TITLE
Time to release new version?

### ISSUE THREAD

**Issue by Yikun** [lh3/bwa#401]
We are trying to create some bioconda package [1] on Linux aarch64 which depends on `bwa`, but hit the bug which https://github.com/lh3/bwa/pull/359 solved.

Is there any chance to bump a version? Then we will upgrade the bwa in bioconda channel [2].

[1] https://github.com/bioconda/bioconda-recipes/blob/master/recipes/abeona/meta.yaml#L28
[2] https://github.com/bioconda/bioconda-recipes/tree/master/recipes/bwa

**Comment by Yikun** [comment]
cc @martin-g

**Comment by emiliofernandes** [comment]
A release would be very welcome indeed!
Currently we build from `master` hoping that there won't be a commit introducing a regression.
There isn't much activity in the project so the chances for regressions are low! But we would feel calmer if there is a proper release/tag with the ARM64 improvements!
Thank you!

**Comment by kErica** [comment]
Following

**Comment by martin-g** [comment]
+1 from me too!

**Comment by jmarshall** [comment]
Bioconda now supports linux-aarch64 and is actively building packages for that platform. PR bioconda/bioconda-recipes#46461 activates this for the **bwa** recipe, but fails because the most recent bwa release is from 2017 and does not include PR #359's ARM port — along with several other build fixes for modern compilers that have also been added since.

It would be greatly appreciated by many if there was a new BWA release made that includes the ARM port and the `extern rle_auxtab` build fix. A new release should also include #346 and especially #348 (which also fixes a bug in `@HD` header ordering), and I have identified another dozen low-risk PRs that fix spelling and documentation and additional build issues. (Namely: an updated version of #26, #212, #278, #286, a revision of #288, #291 after verification, #308 after verification, #311, #346, #348, #390, #414.)

@lh3: If you wanted to make me an external contributor on this repo, I would be happy to do the work of merging these PRs in a tidy way to facilitate an eventual release.

**Comment by bgruening** [comment]
@lh3 on Bioconda we get a lot of requests for a new release and some pressure to spin our own release with mentioned patches here. We would very much to avoid that, but that means we need a new release here.

Could you please look at this or outline how you imagine this essential software should be maintained in the future?

Thanks a lot!

**Comment by lh3** [comment]
Thanks for the push. Done.

**Comment by bgruening** [comment]
Great, thanks a lot!
