### ISSUE TITLE
error with long comment+name

### ISSUE THREAD

**Issue by brentp** [lh3/bwa#79]
Running as:
```
bwa mem -pC $base long.fq.gz
```
gives nonsense for the read name (and alignemtns)

If I do:
```
bwa mem -pC  $base  <(zcat long.fq.gz | awk '{ print substr($0, 0, 300) }')
```

or any value smaller, then it aligns and outputs as expected.

[long.fq.gz](https://github.com/lh3/bwa/files/374629/long.fq.gz)

**Comment by dnbh** [comment]
I think the actual problem is that one can't actually parse your fastq records in, with or without a comment, because your seq and quality fields are of different lengths.

I used the same feature heavily in BMFtools, and I had no problems appending comment in the form of tags in excess of 1000 characters per read.

**Comment by brentp** [comment]
doh. thanks.
